# Railway deployment configuration for YouTube Summarizer
# This is a full-stack app with Python backend and React frontend

[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm-9_x", "ffmpeg", "python311Packages.pip"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "python3 -m pip install -r requirements.txt",
    "npm ci",
    "npm run build"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"