# Railway deployment configuration for YouTube Summarizer
# This is a full-stack app with Python backend and React frontend

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "ffmpeg"]

[phases.install]
cmds = [
    "curl -LsSf https://astral.sh/uv/install.sh | sh",
    "source ~/.cargo/env", 
    "uv sync",
    "npm ci",
    "npm run build"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python3 -m uvicorn app:app --host 0.0.0.0 --port $PORT"