# Working nixpacks configuration for YouTube Summarizer
# Single service deployment - backend + frontend (no UV issues)

[phases.setup]
nixPkgs = ["python311", "nodejs_18", "npm-9_x", "ffmpeg"]

[phases.install]
dependsOn = ["setup"]
cmds = [
    "pip install -r requirements.txt",
    "npm ci",
    "npm run build"
]

[phases.build]
dependsOn = ["install"]

[start]
cmd = "python -m uvicorn app:app --host 0.0.0.0 --port $PORT"